Repository JuliaLang/JuliaSyntax.jl, pull requests merged in 2024-07, with the labels that each got.

#452 Hashing fixup, equality support, and serialization support
  Project.toml
  src/green_tree.jl
  src/kinds.jl
  src/source_files.jl
  src/syntax_tree.jl
  test/runtests.jl
  test/serialization.jl
Labels: enhancement

#455 Fix emitting comments followed by `\r\n`
  src/tokenize.jl
  test/tokenize.jl
Labels: tokenizer

#462 Fix parsing of `-1::Int` - signed literals with type assertions
  src/parser.jl
  test/parser.jl
Labels: bug, parser

#463 Move overload of Base.range() to JuliaSyntax.byte_range()
  docs/src/api.md
  src/diagnostics.jl
  src/expr.jl
  src/syntax_tree.jl
  tools/check_all_packages.jl
Labels: breaking

#433 Change AST for iterations to use `iteration` kind
  docs/src/reference.md
  src/expr.jl
  src/kinds.jl
  src/parser.jl
  test/parser.jl
Labels: AST, breaking

#466 Use `K"function"` for short form function AST
  docs/src/api.md
  src/expr.jl
  src/parse_stream.jl
  src/parser.jl
  test/parse_packages.jl
  test/parse_stream.jl
  test/parser.jl
  test/test_utils.jl
Labels: AST, breaking
