Repository JuliaLang/JuliaSyntax.jl, pull requests merged in 2024-08, with the labels that each got.

#456 Allow macrocall in function def syntax
  src/parser.jl
  test/diagnostics.jl
  test/parser.jl
Labels: parser, syntax change

#483 Rename `haschildren()` to `is_leaf()`
  src/expr.jl
  src/green_tree.jl
  src/hooks.jl
  src/syntax_tree.jl
  test/green_node.jl
  test/test_utils.jl
Labels: breaking

#488 Replace K"true" and K"false" with K"Bool"
  src/expr.jl
  src/kinds.jl
  src/literal_parsing.jl
  src/parser.jl
  src/syntax_tree.jl
  src/tokenize.jl
  test/parser.jl
  test/tokenize.jl
Labels: AST, breaking
